name: Build Windows Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Tauri app for Windows
        run: npm run tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tauri-windows-build
          path: src-tauri/target/release/bundle/msi  # 根據你實際的輸出路徑調整
